import type { PageLayout } from "@/types/pageLayout";

export const DEFAULT_DASHBOARD_LAYOUT: PageLayout = {
  widgets: [
    {
      id: "stat-total-students",
      type: "stat",
      title: "Total Students",
      subtitle: "Across all courses",
      span: 1,
      visible: true,
      dataSource: "kpi-total-students",
      icon: "Users",
      colors: ["#1a3a5c"],
    },
    {
      id: "stat-active-students",
      type: "stat",
      title: "Active Students",
      subtitle: "Currently enrolled",
      span: 1,
      visible: true,
      dataSource: "kpi-active-students",
      icon: "CheckCircle2",
      colors: ["#059669"],
    },
    {
      id: "stat-new-admissions",
      type: "stat",
      title: "New Admissions",
      subtitle: "This month",
      span: 1,
      visible: true,
      dataSource: "kpi-new-admissions",
      icon: "UserPlus",
      colors: ["#7c3aed"],
    },
    {
      id: "stat-fees-due",
      type: "stat",
      title: "Fees Due",
      subtitle: "Outstanding balance",
      span: 1,
      visible: true,
      dataSource: "kpi-fees-due",
      icon: "AlertCircle",
      colors: ["#ef4444"],
    },
    {
      id: "stat-fees-collected",
      type: "stat",
      title: "Fees Collected",
      subtitle: "This academic year",
      span: 1,
      visible: true,
      dataSource: "kpi-fees-collected",
      icon: "Wallet",
      colors: ["#d97706"],
    },
    {
      id: "stat-courses",
      type: "stat",
      title: "Total Courses",
      subtitle: "Active courses",
      span: 1,
      visible: true,
      dataSource: "kpi-courses",
      icon: "BookOpen",
      colors: ["#0d9488"],
    },
    {
      id: "stat-batches",
      type: "stat",
      title: "Upcoming Batches",
      subtitle: "Ongoing batches",
      span: 1,
      visible: true,
      dataSource: "kpi-batches",
      icon: "Layers",
      colors: ["#4f46e5"],
    },
    {
      id: "stat-today-classes",
      type: "stat",
      title: "Today's Classes",
      subtitle: "Ongoing now",
      span: 1,
      visible: true,
      dataSource: "kpi-today-classes",
      icon: "Calendar",
      colors: ["#f43f5e"],
    },
    {
      id: "chart-enrollment",
      type: "area",
      title: "Student Enrollment Trend",
      subtitle: "Last 7 months",
      span: 2,
      visible: true,
      dataSource: "enrollment-trend",
      colors: ["#1a3a5c"],
    },
    {
      id: "chart-course-pie",
      type: "pie",
      title: "Enrollment by Course",
      span: 1,
      visible: true,
      dataSource: "course-enrollment",
      colors: ["#1a3a5c", "#c87d1a", "#2d6a4f", "#7c3d8f", "#c0392b", "#2563eb", "#dc2626"],
    },
    {
      id: "chart-fees",
      type: "bar",
      title: "Fee Collection vs Due",
      subtitle: "Monthly overview",
      span: 2,
      visible: true,
      dataSource: "fee-trend",
      colors: ["#1a3a5c", "#c0392b"],
    },
    {
      id: "list-today-classes",
      type: "list",
      title: "Today's Classes",
      span: 1,
      visible: true,
      dataSource: "today-classes",
    },
  ],
};
